version: '3'
services:
  mongo:
    image: mongo:3.6
    ports:
     - "27017:27017"
    volumes:
     - ./data:/data/db
    container_name: mongo

  app:
    build: ./
    ports:
     - "8080:8080"
    restart: on-failure
    env_file:
     - .env
    links:
     - mongo
    depends_on:
     - mongo
    container_name: leantech_challenge